### ISSUE TITLE
dnsparks.t: -T and -B not implemented on filehandles 

### ISSUE THREAD

**Issue by iabyn** [ap/Text-Tabs#2]
I've temporarily added the following skip to t/dnsparks.t in the 2021.0717 version of Text::Tabs currently in blead. I have no particular opinion on what the proper fix should be.

```
diff --git a/cpan/Text-Tabs/t/dnsparks.t b/cpan/Text-Tabs/t/dnsparks.t
index 2e6e6aeaa2..2f8bc16454 100644
--- a/cpan/Text-Tabs/t/dnsparks.t
+++ b/cpan/Text-Tabs/t/dnsparks.t
@@ -1,6 +1,15 @@
 use strict; use warnings;
 
 BEGIN {
+        # XXX workaround for bleadperl smokes using PERLIO=stdio:
+        #
+        # $ PERLIO=stdio ./perl -Ilib  cpan/Text-Tabs/t/dnsparks.t
+        # -T and -B not implemented on filehandles at cpan/Text-Tabs/t/dnsparks.t line 130
+
+	if ($ENV{PERLIO} eq 'stdio') {
+		print "1..0 # Skipped: stdio not supported\n";
+		exit;
+	}
 	if ($ENV{HARNESS_ACTIVE}) {
 		print "1..0 # Skipped: not a regression test\n";
 		exit;
```

**Comment by ap** [comment]
Note that this test was only added to core some weeks ago. Please simply just remove this test from core again.

I will be making a release that moves this test from `t` to `xt` myself, so the next update of the dist in core will cause it to go away anyway. As you can see at the top of the test, it really wants to be an author test anyway – it just predates the `xt` convention by many years so it wasn’t initially placed there.

The patch I will not apply, since the `-T` check is only used as a heuristic for how interactively the test is being run, and skipping the test based on whether that heuristic will work doesn’t make any sense. I think I’ll just delete the `-T` check entirely and use a fixed value.

**Comment by ap** [comment]
> I will be making a release that moves this test from `t` to `xt` myself

Done. Release 2021.0804 is winding its way to CPAN.

**Comment by ap** [comment]
> Note that this test was only added to core some weeks ago. Please simply just remove this test from core again.

In fact it shouldn’t have been added in the first place:

1. Perl/perl5@af6492bf9e9f3e5024e49941789a1c85db7d4906
2. Perl/perl5@e7b92d54220380e79a3e6d6717958415a905ee7e
