### ISSUE TITLE
This shouldn't happen

### ISSUE THREAD

**Issue by mariopaumann** [ap/Text-Tabs#4]
After upgrading to the newest Text::Wrap lib we regularly get now

'This shouldn't happen at /appl/sw/perl-5.24.0-1/perl-5.24.0/lib/5.24.0/Text/Wrap.pm line 74'

do i need to provide a testcase for this ?

**Comment by ap** [comment]
Can you provide one that doesn’t trigger the warning when run against an older release but does against the latest? That would be much appreciated.

**Comment by mariopaumann** [comment]
ok thank you. made one attached. Here's the output.
btw. it's not a warning. it dies.

```
$> perl wrap.pl
2021.0814
This shouldn't happen at /Users/mario/git/perl/lib/perl5/Text/Wrap.pm line 74.
```

```
$> perl wrap.pl
2013.0523
wrapped ️ Taglia Unica
```

```
$> cat wrap.pl
#! /usr/bin/env perl

use strict;
use warnings;

use Text::Wrap;

binmode STDOUT, ':encoding(UTF-8)';

print $Text::Wrap::VERSION, "\n";
printf "wrapped %s\n", Text::Wrap::wrap( "", "", "\x{fe0f} Taglia Unica" );
```

**Comment by ap** [comment]
Thank you!

**Comment by mariopaumann** [comment]
@ap can you predict if and when you can publish a fixed version ? So that i can schedule if i should continue using the previous release ? Thank you!

**Comment by ap** [comment]
I consider this fairly important so I hope to get to it within a few days. But it might be more like a few weeks, depending on spare capacity.

**Comment by mariopaumann** [comment]
it dies quite frequently on our side, yes, but we can rollback to an older version meanwhile

**Comment by mariopaumann** [comment]
@ap meanwhile i will revert to old version permanently now. i keep ticket open though

**Comment by demerphq** [comment]
@ap did you fix this ever?

**Comment by ap** [comment]
Not yet, that’s why the issue is still open. (I keep my trackers maintained.)

**Comment by demerphq** [comment]
> Not yet, that’s why the issue is still open. (I keep my trackers maintained.)

Sorry, didn't meant come across as snarky, its just i noticed you said 'I consider this fairly important so I hope to get to it within a few days.', on Aug 9, 2022, and it is now Mar 4, 2023. So I wondered if you had fixed it and forgot to close the ticket.  :-) I think you'll admit a fair question to ask.

FWIW, I only looked at the ticket because the title is kinda ambiguous and I wanted to check if the thing I wanted to report was already known or not. Maybe edit the bug title?

**Comment by ap** [comment]
I was trying not to come across as snarky myself. 🙂

I had been “hoping” because I had a lot on my plate at the time. On top of that, Memoize was competing for the attention I could devote to CPAN around then as well. I must admit I also temporarily burned out on this dist because it has been painfully complicated and tricky every step of the way. (I know, I wouldn’t have believed that either. How could Text::Tabs be anything but trivial?) (For comparison, Memoize was downright pleasant – even with the tons of “deferred maintenance” to catch up on.)

So it fell through the cracks. There’s no question I need to rectify that.

**Comment by ap** [comment]
I’m moving issue tracking for this dist back to CPAN RT.

This ticket is now https://rt.cpan.org/Ticket/Display.html?id=148291 (@mariopaumann)
